import type { AppData, AppSettings } from "../types";

export const defaultSettings: AppSettings = {
  launchAtStartup: false,
  silentLaunch: false,
  autoCheckUpdate: true,
  minimizeOnClose: true,
  autoConnect: true,
  language: "简体中文",
  systemProxy: false,
  allowLan: false,
  proxyMode: "规则模式",
  tunMode: false,
  ipv6: false,
  firewall: false,
  mixedPort: 7890,
  httpPort: 7892,
  uiSecret: "",
  socksPort: 7891,
  controllerPort: 9090,
  maxConnections: 32,
  core: "Mihomo",
  coreStartTiming: "手动启动",
  coreMode: "规则模式",
  coreIpv6: false,
  logLevel: "信息 (Info)",
  udpForward: true,
  debugPort: 9090,
  tcpKeepAlive: true,
  externalController: "127.0.0.1:9090",
  configOverride: "",
  bypassLan: true,
  bypassChina: true,
  dnsStrategy: "使用内核 (Fake-IP)",
  etag: true,
  unifiedDelay: true,
  connectNearest: true,
  networkStack: "Mixed",
  autoRoute: true,
  strictRoute: false,
  networkInterface: "系统默认",
  bindAddress: "0.0.0.0",
  processMode: "Always",
  processModeDefaultV2: true,
  bypassMainland: true,
  dnsEnabled: true,
  dnsIpv6: false,
  dnsListen: "0.0.0.0:1053",
  enhancedMode: "Fake-IP",
  overrideSystemDns: false,
  useHosts: true,
  defaultDns: ["223.5.5.5", "119.29.29.29"],
  proxyDns: ["tls://1.1.1.1", "https://dns.google/dns-query"],
  directDns: ["223.5.5.5", "119.29.29.29"],
  dnsPolicy: "优先使用代理 DNS",
  fallbackDns: ["1.0.0.1", "8.8.8.8"],
  geoIpFilter: true,
  geoSiteFilter: true,
  cidrWhitelist: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16",
  domainWhitelist: "*.lan, localhost, *.local",
  proxyOnlyFallback: false,
  fakeIpRange: "198.18.0.1/16",
  fakeIpFilter: "*.lan\nlocalhost.ptlogin2.qq.com\nstun.*.*",
  followRules: true,
  dnsCache: true,
  ecs: false,
  nameServerPolicy: "geosite:private, direct\ngeosite:cn, [223.5.5.5, 119.29.29.29]",
  uiTheme: "浅色",
  uiScale: "100%",
  roundedStyle: "标准",
  glassEffect: true,
  uiLanguage: "简体中文",
  defaultPage: "总览",
  navCollapsed: false,
  compactMode: false,
  cardSpacing: "标准",
  listDensity: "舒适",
  showStatusFooter: true,
  closeToTray: true,
  minimizeToTray: false,
  showTrayIcon: true,
  uiAnimation: true,
  operationHints: true,
  shortcutHints: true,
  logOutput: "文本",
  timestamp: true,
  showSource: true,
  colorLogs: true,
  silentCoreLog: false,
  logToFile: true,
  logPath: "~/logs/clash-mg/app.log",
  maxLogSize: "10 MB",
  retentionDays: 7,
  rotateLogs: true,
  clearOldLogs: false,
  recordConnections: true,
  recordDns: false,
  recordRules: true,
  recordProxySwitch: true,
  recordTun: false,
  filterKeywords: "",
  excludeKeywords: "healthcheck, ping",
  realtimeScroll: true,
  maxLogRows: 1000,
  showLevelTags: true,
  collapseDuplicates: false,
  doubleClickCopy: true,
};

export function createEmptyAppData(): AppData {
  return {
    themeMode: "light",
    accent: "#12b8c4",
    sidebarCollapsed: false,
    connected: false,
    selectedNodeId: "",
    selectedGroupId: "",
    nodes: [],
    groups: [],
    proxyGroupOverrides: [],
    subscriptions: [],
    rules: [],
    ruleOverrides: [],
    connections: [],
    logs: [],
    activities: [],
    settings: { ...defaultSettings },
    domainOverrides: [],
    requestOverrides: [],
    responseOverrides: [],
    trafficHistory: [],
    runtime: {
      controllerConnected: false,
      controllerUrl: "http://127.0.0.1:9090",
      coreVersion: "未连接",
      uploadTotal: "0 B",
      downloadTotal: "0 B",
      lastSync: new Date().toLocaleTimeString("zh-CN", { hour12: false }),
      tunEnabled: false,
      processMode: "未连接",
    },
  };
}
